/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Misc.Calculator;

/**
 *
 * @author Cliftonb
 */
public class CalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton10 = new javax.swing.JButton();
                desktopPane = new javax.swing.JDesktopPane();
                jPanel2 = new javax.swing.JPanel();
                display = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                percentBut = new javax.swing.JButton();
                clearAllBut = new javax.swing.JButton();
                clearBut = new javax.swing.JButton();
                backBut = new javax.swing.JButton();
                invertBut = new javax.swing.JButton();
                squareBut = new javax.swing.JButton();
                sqrtBut = new javax.swing.JButton();
                divideBut = new javax.swing.JButton();
                sevenBut = new javax.swing.JButton();
                eightBut = new javax.swing.JButton();
                nineBut = new javax.swing.JButton();
                multiplyBut = new javax.swing.JButton();
                fourBut = new javax.swing.JButton();
                fiveBut = new javax.swing.JButton();
                sixBut = new javax.swing.JButton();
                plusBut = new javax.swing.JButton();
                oneBut = new javax.swing.JButton();
                twoBut = new javax.swing.JButton();
                threeBut = new javax.swing.JButton();
                minusBut = new javax.swing.JButton();
                negBut = new javax.swing.JButton();
                zeroBut = new javax.swing.JButton();
                decimalBut = new javax.swing.JButton();
                equalsBut = new javax.swing.JButton();
                menuBar = new javax.swing.JMenuBar();
                fileMenu = new javax.swing.JMenu();
                openMenuItem = new javax.swing.JMenuItem();
                saveMenuItem = new javax.swing.JMenuItem();
                saveAsMenuItem = new javax.swing.JMenuItem();
                exitMenuItem = new javax.swing.JMenuItem();
                editMenu = new javax.swing.JMenu();
                cutMenuItem = new javax.swing.JMenuItem();
                copyMenuItem = new javax.swing.JMenuItem();
                pasteMenuItem = new javax.swing.JMenuItem();
                deleteMenuItem = new javax.swing.JMenuItem();
                helpMenu = new javax.swing.JMenu();
                contentMenuItem = new javax.swing.JMenuItem();
                aboutMenuItem = new javax.swing.JMenuItem();

                jButton10.setText("jButton10");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                display.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
                display.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                displayActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                );

                desktopPane.add(jPanel2);
                jPanel2.setBounds(0, 0, 270, 80);

                jPanel1.setLayout(new java.awt.GridLayout(6, 4, 1, 1));

                percentBut.setText("%");
                jPanel1.add(percentBut);

                clearAllBut.setText("CE");
                jPanel1.add(clearAllBut);

                clearBut.setText("C");
                jPanel1.add(clearBut);

                backBut.setText("<-");
                jPanel1.add(backBut);

                invertBut.setText("1/x");
                jPanel1.add(invertBut);

                squareBut.setText("x^2");
                jPanel1.add(squareBut);

                sqrtBut.setText("sqrt");
                jPanel1.add(sqrtBut);

                divideBut.setText("/");
                divideBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                divideButActionPerformed(evt);
                        }
                });
                jPanel1.add(divideBut);

                sevenBut.setText("7");
                sevenBut.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                sevenButMouseClicked(evt);
                        }
                });
                sevenBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sevenButActionPerformed(evt);
                        }
                });
                jPanel1.add(sevenBut);

                eightBut.setText("8");
                eightBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                eightButActionPerformed(evt);
                        }
                });
                jPanel1.add(eightBut);

                nineBut.setText("9");
                nineBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nineButActionPerformed(evt);
                        }
                });
                jPanel1.add(nineBut);

                multiplyBut.setText("x");
                multiplyBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                multiplyButActionPerformed(evt);
                        }
                });
                jPanel1.add(multiplyBut);

                fourBut.setText("4");
                fourBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fourButActionPerformed(evt);
                        }
                });
                jPanel1.add(fourBut);

                fiveBut.setText("5");
                fiveBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fiveButActionPerformed(evt);
                        }
                });
                jPanel1.add(fiveBut);

                sixBut.setText("6");
                sixBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sixButActionPerformed(evt);
                        }
                });
                jPanel1.add(sixBut);

                plusBut.setText("+");
                plusBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                plusButActionPerformed(evt);
                        }
                });
                jPanel1.add(plusBut);

                oneBut.setText("1");
                oneBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                oneButActionPerformed(evt);
                        }
                });
                jPanel1.add(oneBut);

                twoBut.setText("2");
                twoBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                twoButActionPerformed(evt);
                        }
                });
                jPanel1.add(twoBut);

                threeBut.setText("3");
                threeBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                threeButActionPerformed(evt);
                        }
                });
                jPanel1.add(threeBut);

                minusBut.setText("-");
                minusBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                minusButActionPerformed(evt);
                        }
                });
                jPanel1.add(minusBut);

                negBut.setText("+/-");
                jPanel1.add(negBut);

                zeroBut.setText("0");
                zeroBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                zeroButActionPerformed(evt);
                        }
                });
                jPanel1.add(zeroBut);

                decimalBut.setText(",");
                jPanel1.add(decimalBut);

                equalsBut.setText("=");
                equalsBut.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                equalsButActionPerformed(evt);
                        }
                });
                jPanel1.add(equalsBut);

                desktopPane.add(jPanel1);
                jPanel1.setBounds(0, 80, 270, 300);

                fileMenu.setMnemonic('f');
                fileMenu.setText("File");

                openMenuItem.setMnemonic('o');
                openMenuItem.setText("Open");
                fileMenu.add(openMenuItem);

                saveMenuItem.setMnemonic('s');
                saveMenuItem.setText("Save");
                fileMenu.add(saveMenuItem);

                saveAsMenuItem.setMnemonic('a');
                saveAsMenuItem.setText("Save As ...");
                saveAsMenuItem.setDisplayedMnemonicIndex(5);
                fileMenu.add(saveAsMenuItem);

                exitMenuItem.setMnemonic('x');
                exitMenuItem.setText("Exit");
                exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(exitMenuItem);

                menuBar.add(fileMenu);

                editMenu.setMnemonic('e');
                editMenu.setText("Edit");

                cutMenuItem.setMnemonic('t');
                cutMenuItem.setText("Cut");
                editMenu.add(cutMenuItem);

                copyMenuItem.setMnemonic('y');
                copyMenuItem.setText("Copy");
                editMenu.add(copyMenuItem);

                pasteMenuItem.setMnemonic('p');
                pasteMenuItem.setText("Paste");
                editMenu.add(pasteMenuItem);

                deleteMenuItem.setMnemonic('d');
                deleteMenuItem.setText("Delete");
                editMenu.add(deleteMenuItem);

                menuBar.add(editMenu);

                helpMenu.setMnemonic('h');
                helpMenu.setText("Help");

                contentMenuItem.setMnemonic('c');
                contentMenuItem.setText("Contents");
                helpMenu.add(contentMenuItem);

                aboutMenuItem.setMnemonic('a');
                aboutMenuItem.setText("About");
                helpMenu.add(aboutMenuItem);

                menuBar.add(helpMenu);

                setJMenuBar(menuBar);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void multiplyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButActionPerformed
        previousNumber = currentNumber;
        currentNumber = Double.parseDouble(currentDisplay);
        currentOperation = '*';

        if (firstNum) {
            firstNum = false;
            currentDisplay = "";
            display.setText("");
        } else {
            //do previous calc, set current operation to *
            completeCalculation();
            //reset the saved num string
            currentDisplay = "";
            display.setText("" + currentNumber);
        }
    }//GEN-LAST:event_multiplyButActionPerformed

    private void sevenButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButActionPerformed
        currentDisplay += "7";
        display.setText(currentDisplay);
    }//GEN-LAST:event_sevenButActionPerformed

    private void eightButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButActionPerformed
        currentDisplay += "8";
        display.setText(currentDisplay);
    }//GEN-LAST:event_eightButActionPerformed

    private void nineButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButActionPerformed
        currentDisplay += "9";
        display.setText(currentDisplay);
    }//GEN-LAST:event_nineButActionPerformed

    private void sevenButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButMouseClicked
    }//GEN-LAST:event_sevenButMouseClicked

    private void fourButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButActionPerformed
        currentDisplay += "4";
        display.setText(currentDisplay);
    }//GEN-LAST:event_fourButActionPerformed

    private void fiveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButActionPerformed
        currentDisplay += "7";
        display.setText(currentDisplay);
    }//GEN-LAST:event_fiveButActionPerformed

    private void sixButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButActionPerformed
        currentDisplay += "6";
        display.setText(currentDisplay);
    }//GEN-LAST:event_sixButActionPerformed

    private void oneButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButActionPerformed
        currentDisplay += "1";
        display.setText(currentDisplay);
    }//GEN-LAST:event_oneButActionPerformed

    private void twoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButActionPerformed
        currentDisplay += "2";
        display.setText(currentDisplay);
    }//GEN-LAST:event_twoButActionPerformed

    private void threeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButActionPerformed
        currentDisplay += "3";
        display.setText(currentDisplay);
    }//GEN-LAST:event_threeButActionPerformed

    private void zeroButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButActionPerformed
        currentDisplay += "0";
        display.setText(currentDisplay);
    }//GEN-LAST:event_zeroButActionPerformed

    private void divideButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButActionPerformed
        previousNumber = currentNumber;
        currentNumber = Double.parseDouble(currentDisplay);
        currentOperation = '/';

        if (firstNum) {
            firstNum = false;
            currentDisplay = "";
            display.setText("");
        } else {
            //do previous calc, set current operation to * 
            completeCalculation();
            //reset the saved num string
            currentDisplay = "";
            display.setText("" + currentNumber);
        }
    }//GEN-LAST:event_divideButActionPerformed

    private void minusButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButActionPerformed
        previousNumber = currentNumber;
        currentNumber = Double.parseDouble(currentDisplay);
        currentOperation = '-';
        
        if(firstNum){
            firstNum = false;
            currentDisplay = "";
            display.setText("");
        }
        else{
            //do previous calc, set current operation to *
            completeCalculation();
            //reset the saved num string
            currentDisplay = "";
            display.setText("" + currentNumber);
        }
    }//GEN-LAST:event_minusButActionPerformed

    private void plusButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButActionPerformed
        previousNumber = currentNumber;
        currentNumber = Double.parseDouble(currentDisplay);
        currentOperation = '+';
        
        if(firstNum){
            firstNum = false;
            currentDisplay = "";
            display.setText("");
        }
        else{
            //do previous calc, set current operation to *
            completeCalculation();
            //reset the saved num string
            currentDisplay = "";
            display.setText("" + currentNumber);
        }
    }//GEN-LAST:event_plusButActionPerformed

    private void equalsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButActionPerformed
        previousNumber = currentNumber;
        currentNumber = Double.parseDouble(currentDisplay);
        completeCalculation();
        currentDisplay = "";
        display.setText("" + currentNumber);
    }//GEN-LAST:event_equalsButActionPerformed

    private void completeCalculation() {
        switch (previousOperation) {
            case '*':
                currentNumber = previousNumber * currentNumber;
                break;
            case '/':
                currentNumber = previousNumber / currentNumber;
                break;
            case '+':
                currentNumber = previousNumber + currentNumber;
                break;
            case '-':
                currentNumber = previousNumber - currentNumber;
                break;
        }

        previousOperation = currentOperation;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem aboutMenuItem;
        private javax.swing.JButton backBut;
        private javax.swing.JButton clearAllBut;
        private javax.swing.JButton clearBut;
        private javax.swing.JMenuItem contentMenuItem;
        private javax.swing.JMenuItem copyMenuItem;
        private javax.swing.JMenuItem cutMenuItem;
        private javax.swing.JButton decimalBut;
        private javax.swing.JMenuItem deleteMenuItem;
        private javax.swing.JDesktopPane desktopPane;
        private javax.swing.JTextField display;
        private javax.swing.JButton divideBut;
        private javax.swing.JMenu editMenu;
        private javax.swing.JButton eightBut;
        private javax.swing.JButton equalsBut;
        private javax.swing.JMenuItem exitMenuItem;
        private javax.swing.JMenu fileMenu;
        private javax.swing.JButton fiveBut;
        private javax.swing.JButton fourBut;
        private javax.swing.JMenu helpMenu;
        private javax.swing.JButton invertBut;
        private javax.swing.JButton jButton10;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JMenuBar menuBar;
        private javax.swing.JButton minusBut;
        private javax.swing.JButton multiplyBut;
        private javax.swing.JButton negBut;
        private javax.swing.JButton nineBut;
        private javax.swing.JButton oneBut;
        private javax.swing.JMenuItem openMenuItem;
        private javax.swing.JMenuItem pasteMenuItem;
        private javax.swing.JButton percentBut;
        private javax.swing.JButton plusBut;
        private javax.swing.JMenuItem saveAsMenuItem;
        private javax.swing.JMenuItem saveMenuItem;
        private javax.swing.JButton sevenBut;
        private javax.swing.JButton sixBut;
        private javax.swing.JButton sqrtBut;
        private javax.swing.JButton squareBut;
        private javax.swing.JButton threeBut;
        private javax.swing.JButton twoBut;
        private javax.swing.JButton zeroBut;
        // End of variables declaration//GEN-END:variables

    private String currentDisplay = "";
    private double currentNumber = 0;
    private double previousNumber = 0;
    private boolean firstNum = true;
    private char currentOperation;
    private char previousOperation;

}
